### ISSUE TITLE
Dockerfile.minerva currently produces a bad image

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua_app_stack#12]
In `geneontology/minerva:v4`:
```
bash-4.4$ /app/run.sh 
bash: /app/run.sh: /bin/bash\nset: bad interpreter: No such file or directory
bash-4.4$ 
```

**Comment by kltm** [comment]
Tagging @mugitty

**Comment by kltm** [comment]
It seems like we are now having issues with the minerva runner image taking 2GB only. 
I'm not sure how this even worked, but I'm guessing that the previous version of the script didn't pass in the variable somehow and the default java value was used. Now that the script was fixed, it is using the explicit 2GB, which causes a heap error pretty quickly. We need to set this up to use the available memory (which I believe was 24GB).

**Comment by kltm** [comment]
I believe this is now fixed?

**Comment by mugitty** [comment]
@kltm , this was fixed with [Minerva release](https://hub.docker.com/layers/geneontology/minerva/v7/images/sha256-85bbd7ef67134beef53c2fef303aa2ba4145d058eeb45e3934791afabdaf8c51?context=explore)
