### ISSUE TITLE
Ensure at least Java 11 in Noctua-in-AWS images

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua_app_stack#9]
A chained on requirement for the future from https://github.com/geneontology/minerva/pull/546 , we need to make sure that future versions of the minerva stack have access to at least Java 11.

Tagging @mugitty and @balhoff

**Comment by balhoff** [comment]
I think it would be wise to see if we can start quite a bit further ahead than 11 even, if we are testing changes. Java 11 itself is pretty old now. Current LTS is Java 21, and it has been out for a year.

**Comment by kltm** [comment]
@balhoff Ideally, we are following an official release, rather than building customizing our own images. For the time being, given the requirements, if there is nothing else coming up, the easiest thing to do here is to got with the last official maven/openjdk release: `maven:3.8.7-openjdk-18`, which follows what is going on now. Otherwise, if there is something we'll be needing a later version for in the near future, we'll be doing something a little more custom with the last Ubuntu LTS: 24.04.

**Comment by kltm** [comment]
@mugitty Can correct me if I'm wrong, but this is now the case.

**Comment by mugitty** [comment]
@kltm, Minerva is now at jdk:17.  [dockerfile for minerva](https://github.com/geneontology/noctua_app_stack/blob/ef86f791a81eb82b9a01ffa40072cb6e34a60511/docker/Dockerfile.minerva#L1C1-L4C1)
